version: '3'

services:
  # Service WordPress
  wordpress:
    image: wordpress:perso
    container_name: conteneur-wordpress
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - "8000:8000"
    restart: always
    networks:
      - reseau-eval

  # Service MySQL (base de données)
  mysql:
    image: mysql:perso
    container_name: conteneur-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always
    networks:
      - reseau-eval

  # Service phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:perso
    container_name: conteneur-phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8002-8002"
    restart: always
    depends_on:
      - mysql
    networks:
      - reseau-eval

networks:
  reseau-eval:
    driver: bridge
