# Utiliser une image MySQL
FROM mysql:8.0

# Définir des variables d'environnement pour la configuration de la base de données
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=wordpress
ENV MYSQL_USER=wordpress_user
ENV MYSQL_PASSWORD=wordpress_password

# Exposer le port 8002
EXPOSE 8001
